---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: gphugo/content/posts
  label: Post
  create: all
  match: "**/*"
  exclude: _index.md
- type: directory
  path: gphugo/content
  label: Pages
  create: all
  match: "**/*"
  exclude: posts
upload_dir: gphugo/static/images
public_path: "/gphugo/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: gphugo/public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv/gphugo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public -b localhost
version: 0.71.1
